import os

# General
SECRET_KEY = os.getenv("SECRET_KEY")

# AWS Cognito
COGNITO_CLIENT_ID = os.getenv("COGNITO_CLIENT_ID")
COGNITO_DOMAIN = os.getenv("COGNITO_DOMAIN")
COGNITO_AUTHORIZATION_URL = f"{COGNITO_DOMAIN}/oauth2/authorize"
COGNITO_TOKEN_URL = f"{COGNITO_DOMAIN}/oauth2/token"
COGNITO_REDIRECT_URI = os.getenv("COGNITO_REDIRECT_URI")
COGNITO_LOGOUT_URI = f"{COGNITO_DOMAIN}/logout"
