services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: portfolio_backend_local
    ports:
      - "3000:8000"
    volumes:
      - ./src/backend/:/var/task/backend/
    env_file:
      - .env.local
