AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Backend Service

Resources:
  BackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      Runtime: python3.10
      CodeUri: .
      MemorySize: 512
      Timeout: 15
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        Root:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY
        Proxy:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
    Metadata:
      BuildMethod: python3.10
